import { ImageSource } from "expo-image";

export const sample_foods = [
  {
    id: 1,
    name: "Margherita Pizza",
    price: 3897,
    tags: ["Pizza", "Italian", "Dinner"],
    favorite: true,
    stars: 4.5,
    imageUrl: "/foods/food-1.jpg",
    origins: ["Italy"],
    cookTime: "20",
    desc: "Indulge in the classic flavors of Italy with our Margherita Pizza. This delightful dish features a thin crust topped with fresh tomatoes, mozzarella, and fragrant basil leaves. Each bite is a burst of authentic Italian taste, making it a perfect choice for a satisfying dinner experience.",
  },
  {
    id: 2,
    name: "Chicken Alfredo Pasta",
    price: 4797,
    tags: ["Pasta", "Italian", "Dinner"],
    favorite: false,
    stars: 4.2,
    imageUrl: "/foods/food-2.jpg",
    origins: ["Italy"],
    cookTime: "30",
    desc: "Savor the rich and creamy goodness of our Chicken Alfredo Pasta. Cooked to perfection, this Italian-inspired dish features al dente pasta coated in a velvety Alfredo sauce. Tender pieces of chicken add a savory touch, creating a comforting and flavorful dining experience for pasta enthusiasts.",
  },
  {
    id: 3,
    name: "Vegetarian Stir-Fry",
    price: 3297,
    tags: ["Vegetarian", "Asian", "Lunch"],
    favorite: true,
    stars: 4.8,
    imageUrl: "/foods/food-3.jpg",
    origins: ["Asia"],
    cookTime: "25",
    desc: "Embark on a culinary journey with our Vegetarian Stir-Fry, a delightful Asian-inspired dish. Fresh vegetables are wok-tossed to perfection, creating a colorful and nutritious medley. The combination of vibrant flavors and textures makes it an ideal choice for a satisfying and healthy lunch.",
  },
  {
    id: 4,
    name: "Classic Hamburger",
    price: 2697,
    tags: ["Fast Food", "Lunch", "Hamburger"],
    favorite: false,
    stars: 4,
    imageUrl: "/foods/food-4.jpg",
    origins: ["USA"],
    cookTime: "15",
    desc: "Satisfy your cravings with our Classic Hamburger, an iconic American favorite. This mouthwatering creation features a juicy beef patty, fresh lettuce, ripe tomatoes, and a special sauce, all sandwiched between soft burger buns. It's a timeless choice for a quick and delicious lunch.",
  },
  {
    id: 5,
    name: "Sushi Platter",
    price: 7496.999999999999,
    tags: ["Sushi", "Japanese", "Dinner"],
    favorite: true,
    stars: 4.7,
    imageUrl: "/foods/food-5.jpg",
    origins: ["Japan"],
    cookTime: "40",
    desc: "Elevate your dining experience with our Sushi Platter, a stunning showcase of Japanese culinary artistry. Immerse yourself in the delicate flavors of fresh fish, perfectly seasoned rice, and seaweed. Each piece is a masterpiece, offering a symphony of tastes for a delightful dinner.",
  },
  {
    id: 6,
    name: "Mango Sticky Rice",
    price: 2397,
    tags: ["Dessert", "Thai", "Snack"],
    favorite: false,
    stars: 4.3,
    imageUrl: "/foods/food-6.jpg",
    origins: ["Thailand"],
    cookTime: "15",
    desc: "Treat your taste buds to the exotic sweetness of our Mango Sticky Rice, a beloved Thai dessert. Fragrant sticky rice is paired with ripe mango slices, creating a harmonious blend of textures and flavors. It's a delightful way to conclude your meal or enjoy as a satisfying snack.",
  },
  {
    id: 7,
    name: "Caesar Salad",
    price: 2997,
    tags: ["Salad", "Lunch", "Healthy"],
    favorite: false,
    stars: 4.2,
    imageUrl: "/foods/food-7.jpg",
    origins: ["USA"],
    cookTime: "15",
    desc: "Indulge in a crisp and refreshing experience with our Caesar Salad, a timeless classic from the USA. Crisp romaine lettuce is tossed with savory Caesar dressing, Parmesan cheese, and croutons. This light and healthy salad make for a perfect lunch option, combining simplicity and deliciousness.",
  },
  {
    id: 8,
    name: "Beef Biryani",
    price: 5096.999999999999,
    tags: ["Rice", "Indian", "Dinner"],
    favorite: true,
    stars: 4.6,
    imageUrl: "/foods/food-8.jpg",
    origins: ["India"],
    cookTime: "35",
    desc: "Delight your senses with the aromatic flavors of our Beef Biryani, a traditional Indian dish that is a feast for the palate. Fragrant basmati rice is layered with succulent beef, aromatic spices, and caramelized onions. It's a hearty and satisfying dinner choice, offering a taste of authentic Indian cuisine.",
  },
  {
    id: 9,
    name: "Caprese Salad",
    price: 3597,
    tags: ["Salad", "Italian", "Appetizer"],
    favorite: false,
    stars: 4.4,
    imageUrl: "/foods/food-9.jpg",
    origins: ["Italy"],
    cookTime: "10",
    desc: "Transport yourself to the heart of Italy with our Caprese Salad, a quintessential Italian appetizer. This vibrant salad showcases the simplicity of fresh ingredients—ripe tomatoes, creamy mozzarella, and fragrant basil. Drizzled with extra-virgin olive oil and balsamic glaze, every bite is a burst of Mediterranean flavors, making it an ideal choice for a light and refreshing start to your meal.",
  },
  {
    id: 10,
    name: "Chicken Teriyaki Bowl",
    price: 4197,
    tags: ["Chicken", "Japanese", "Lunch"],
    favorite: true,
    stars: 4.7,
    imageUrl: "/foods/food-10.jpg",
    origins: ["Japan"],
    cookTime: "25",
    desc: "Experience the savory delight of our Chicken Teriyaki Bowl, inspired by the flavors of Japan. Succulent pieces of grilled chicken are glazed in a rich and sweet teriyaki sauce, served atop a bed of steamed rice. This hearty dish is a perfect choice for a satisfying and flavorful lunch, combining the best of Japanese culinary traditions.",
  },
  {
    id: 11,
    name: "Spinach and Feta Stuffed Chicken",
    price: 5696.999999999999,
    tags: ["Chicken", "Mediterranean", "Dinner"],
    favorite: false,
    stars: 4.5,
    imageUrl: "/foods/food-11.jpg",
    origins: ["Mediterranean"],
    cookTime: "40",
    desc: "Indulge in the culinary richness of our Spinach and Feta Stuffed Chicken, a Mediterranean-inspired delicacy. Tender chicken breasts are carefully stuffed with a flavorful combination of spinach and feta cheese, then baked to perfection. This delightful dish is a symphony of textures and tastes, making it a standout choice for a satisfying dinner.",
  },
  {
    id: 12,
    name: "Chocolate Fondue",
    price: 4497,
    tags: ["Dessert", "Swiss", "Chocolate"],
    favorite: true,
    stars: 4.8,
    imageUrl: "/foods/food-12.jpg",
    origins: ["Switzerland"],
    cookTime: "20",
    desc: "Conclude your meal on a sweet note with our Chocolate Fondue, a decadent Swiss dessert experience. Indulge in the velvety richness of melted chocolate served alongside an array of delightful dippables. Whether it's fruits, marshmallows, or cake, each dip is a heavenly blend of sweetness and satisfaction, making it a delightful treat for chocolate lovers.",
  },
];

export const getFoodImage = (name: string) => {
  const foodImg: { [key: string]: ImageSource } = {
    "food-1.jpg": require("../assets/foods/food-1.jpg"),
    "food-2.jpg": require("../assets/foods/food-2.jpg"),
    "food-3.jpg": require("../assets/foods/food-3.jpg"),
    "food-4.jpg": require("../assets/foods/food-4.jpg"),
    "food-5.jpg": require("../assets/foods/food-5.jpg"),
    "food-6.jpg": require("../assets/foods/food-6.jpg"),
    "food-7.jpg": require("../assets/foods/food-7.jpg"),
    "food-8.jpg": require("../assets/foods/food-8.jpg"),
    "food-9.jpg": require("../assets/foods/food-9.jpg"),
    "food-10.jpg": require("../assets/foods/food-10.jpg"),
    "food-11.jpg": require("../assets/foods/food-11.jpg"),
    "food-12.jpg": require("../assets/foods/food-12.jpg"),
  };

  if (foodImg.hasOwnProperty(name)) {
    return foodImg[`${name}`];
  }

  return null;
};

export const sample_tags = [
  { name: "All", count: 6 },
  { name: "Fast Food", count: 4 },
  { name: "Pizza", count: 2 },
  { name: "Lunch", count: 3 },
  { name: "Hamburger", count: 1 },
  { name: "Dessert", count: 1 },
  { name: "Dinner", count: 3 },
  { name: "Pasta", count: 1 },
];
